version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: wealth_tracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379

  crypto-sync-job:
    build:
      context: ./crypto-sync-job/
      target: development
    image: wealth-tracker-services/crypto-sync-job:development
    volumes:
      - ./crypto-sync-job/src:/usr/app/src
    env_file:
      - ./crypto-sync-job/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - redis

  wealth-tracker-api:
    build:
      context: ./wealth-tracker-api/
      target: development
    image: wealth-tracker-services/wealth-tracker-api:development
    ports:
      - 4000:4000
    volumes:
      - ./wealth-tracker-api/src:/usr/app/src
    env_file:
      - ./wealth-tracker-api/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
